# Generated by Django 4.2.7 on 2024-05-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='issues_url',
        ),
    ]
